name: E2E tests
on: [deployment_status]
jobs:
  set_pending:
    name: Register pending E2E tests state
    if: github.event.deployment_status.state == 'pending'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set status to "pending"
        uses: ./.github/actions/set-pr-status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          state: pending
          description: Waiting for E2E results
  run_e2e_tests:
    name: Run E2E tests
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.0-chrome91-ff89
    env:
      TERM: xterm

    steps:
      - uses: actions/checkout@v1

      - name: Run E2E tests
        run: cypress --config baseUrl=${{ github.event.deployment_status.target_url }}

      - name: Set status to "success"
        if: success()
        uses: ./.github/actions/set-pr-status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          state: success
          description: All tests passed

      - name: Set status to "failure"
        if: failure()
        uses: ./.github/actions/set-pr-status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          state: failure
          description: Some tests failed
